#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import os from "os"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const skipRelease = process.argv.includes("--skip-release")
const osFilter = process.argv.filter((a) => a.startsWith("--os=")).map((a) => a.split("=")[1])
const excludeOs = process.argv.filter((a) => a.startsWith("--exclude-os=")).map((a) => a.split("=")[1])

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = allTargets.filter((item) => {
  if (osFilter.length && !osFilter.includes(item.os)) return false
  if (excludeOs.includes(item.os)) return false
  if (!singleFlag) return true
  if (item.os !== process.platform || item.arch !== process.arch) return false
  // When building for the current platform, prefer a single native binary by default.
  // Baseline binaries require additional Bun artifacts and can be flaky to download.
  if (item.avx2 === false) return baselineFlag
  // also skip abi-specific builds for the same reason
  if (item.abi !== undefined) return false
  return true
})

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  // Use anomalyco/bun fork for Windows targets (includes Ctrl+C fix from PR #25876)
  // https://github.com/anomalyco/bun/releases/tag/v1.3.9-opencode.2
  // BUN_COMPILE_TARGET_TARBALL_URL only works for cross-compilation, so we download
  // the fork binary and use executablePath to ensure it works for both native and cross builds.
  // When running natively on Windows (build-cli-windows job), the fork is already the
  // system Bun so executablePath is only needed for the baseline variant.
  const BUN_FORK_VERSION = "1.3.9-opencode.2"
  let forkExePath: string | undefined
  if (item.os === "win32") {
    const native = process.platform === "win32"
    if (!native || item.avx2 === false) {
      const variant = item.avx2 === false ? "bun-windows-x64-baseline" : "bun-windows-x64"
      const forkDir = path.join(os.tmpdir(), "bun-fork", BUN_FORK_VERSION, variant)
      const forkBin = path.join(forkDir, "bun.exe")
      if (!fs.existsSync(forkBin)) {
        const tgzUrl = `https://github.com/anomalyco/bun/releases/download/v${BUN_FORK_VERSION}/${variant}.tgz`
        console.log(`downloading bun fork ${BUN_FORK_VERSION} (${variant})...`)
        console.log(`  ${tgzUrl}`)
        fs.mkdirSync(forkDir, { recursive: true })
        const tgzName = `${variant}.tgz`
        const tgzPath = path.join(forkDir, tgzName)
        const dl = Bun.spawnSync(["curl", "-fSL", "-o", tgzName, tgzUrl], { cwd: forkDir })
        if (dl.exitCode !== 0) throw new Error(`download failed: ${dl.stderr.toString()}`)
        const tar = Bun.spawnSync(["tar", "-xzf", tgzName, "--strip-components=2"], { cwd: forkDir })
        if (tar.exitCode !== 0) throw new Error(`tar extract failed: ${tar.stderr.toString()}`)
        fs.unlinkSync(tgzPath)
      }
      forkExePath = forkBin
      console.log(`using bun fork: ${forkBin}`)
    }
  }

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
      ...(forkExePath ? { executablePath: forkExePath } : {}),
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release && !skipRelease) {
  const archives: string[] = []
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
      archives.push(`./dist/${key}.tar.gz`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
      archives.push(`./dist/${key}.zip`)
    }
  }
  if (archives.length) {
    await $`gh release upload v${Script.version} ${archives} --clobber`
  }
}

export { binaries }
