export namespace Flag {
  export const OPENCODE_AUTO_SHARE = truthy("CLOSEDCODE_AUTO_SHARE") || truthy("OPENCODE_AUTO_SHARE")
  export const OPENCODE_GIT_BASH_PATH = process.env["CLOSEDCODE_GIT_BASH_PATH"] || process.env["OPENCODE_GIT_BASH_PATH"]
  export const OPENCODE_CONFIG = process.env["CLOSEDCODE_CONFIG"] || process.env["OPENCODE_CONFIG"]
  export const OPENCODE_CONFIG_DIR = process.env["CLOSEDCODE_CONFIG_DIR"] || process.env["OPENCODE_CONFIG_DIR"]
  export const OPENCODE_CONFIG_CONTENT = process.env["CLOSEDCODE_CONFIG_CONTENT"] || process.env["OPENCODE_CONFIG_CONTENT"]
  export const OPENCODE_DISABLE_AUTOUPDATE = truthy("CLOSEDCODE_DISABLE_AUTOUPDATE") || truthy("OPENCODE_DISABLE_AUTOUPDATE")
  export const OPENCODE_DISABLE_PRUNE = truthy("CLOSEDCODE_DISABLE_PRUNE") || truthy("OPENCODE_DISABLE_PRUNE")
  export const OPENCODE_DISABLE_TERMINAL_TITLE = truthy("CLOSEDCODE_DISABLE_TERMINAL_TITLE") || truthy("OPENCODE_DISABLE_TERMINAL_TITLE")
  export const OPENCODE_PERMISSION = process.env["CLOSEDCODE_PERMISSION"] || process.env["OPENCODE_PERMISSION"]
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = truthy("CLOSEDCODE_DISABLE_DEFAULT_PLUGINS") || truthy("OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = truthy("CLOSEDCODE_DISABLE_LSP_DOWNLOAD") || truthy("OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("CLOSEDCODE_ENABLE_EXPERIMENTAL_MODELS") || truthy("OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENCODE_DISABLE_AUTOCOMPACT = truthy("CLOSEDCODE_DISABLE_AUTOCOMPACT") || truthy("OPENCODE_DISABLE_AUTOCOMPACT")
  export const OPENCODE_DISABLE_MODELS_FETCH = truthy("CLOSEDCODE_DISABLE_MODELS_FETCH") || truthy("OPENCODE_DISABLE_MODELS_FETCH")
  export const OPENCODE_DISABLE_CLAUDE_CODE = truthy("CLOSEDCODE_DISABLE_CLAUDE_CODE") || truthy("OPENCODE_DISABLE_CLAUDE_CODE")
  export const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT =
    OPENCODE_DISABLE_CLAUDE_CODE || truthy("CLOSEDCODE_DISABLE_CLAUDE_CODE_PROMPT") || truthy("OPENCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
    OPENCODE_DISABLE_CLAUDE_CODE || truthy("CLOSEDCODE_DISABLE_CLAUDE_CODE_SKILLS") || truthy("OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const OPENCODE_FAKE_VCS = process.env["CLOSEDCODE_FAKE_VCS"] || process.env["OPENCODE_FAKE_VCS"]
  export const OPENCODE_CLIENT = process.env["CLOSEDCODE_CLIENT"] || process.env["OPENCODE_CLIENT"] || "cli"

  // Experimental
  export const OPENCODE_EXPERIMENTAL = truthy("CLOSEDCODE_EXPERIMENTAL") || truthy("OPENCODE_EXPERIMENTAL")
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = truthy("CLOSEDCODE_EXPERIMENTAL_FILEWATCHER") || truthy("OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("CLOSEDCODE_EXPERIMENTAL_DISABLE_FILEWATCHER") || truthy("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY =
    OPENCODE_EXPERIMENTAL || truthy("CLOSEDCODE_EXPERIMENTAL_ICON_DISCOVERY") || truthy("OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("CLOSEDCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT") || truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_ENABLE_EXA =
    truthy("CLOSEDCODE_ENABLE_EXA") || truthy("OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_EXA")
  export const OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("CLOSEDCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH") || number("OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("CLOSEDCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS") || number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("CLOSEDCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX") || number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENCODE_EXPERIMENTAL_OXFMT = OPENCODE_EXPERIMENTAL || truthy("CLOSEDCODE_EXPERIMENTAL_OXFMT") || truthy("OPENCODE_EXPERIMENTAL_OXFMT")
  export const OPENCODE_EXPERIMENTAL_LSP_TY = truthy("CLOSEDCODE_EXPERIMENTAL_LSP_TY") || truthy("OPENCODE_EXPERIMENTAL_LSP_TY")
  export const OPENCODE_EXPERIMENTAL_LSP_TOOL = OPENCODE_EXPERIMENTAL || truthy("CLOSEDCODE_EXPERIMENTAL_LSP_TOOL") || truthy("OPENCODE_EXPERIMENTAL_LSP_TOOL")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
